// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
import { Product } from './Product';

export interface Category {
    categoryId: number;
    categoryName: string;
    product: Product[];
}