// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
import { CustomerSetting } from './CustomerSetting';
import { Order } from './Order';

export interface Customer {
    customerId: string;
    companyName: string;
    contactName: string;
    city: string;
    country: string;
    customerSetting: CustomerSetting;
    order: Order[];
}