// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
import { Customer } from './Customer';

export interface CustomerSetting {
    customerId: string;
    setting: string;
    customer: Customer;
}