// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
import { Employee } from './Employee';
import { Territory } from './Territory';

export interface EmployeeTerritories {
    employeeId: number;
    territoryId: string;
    employee: Employee;
    territory: Territory;
}