// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
import { Category } from './Category';
import { OrderDetail } from './OrderDetail';

export interface Product {
    productId: number;
    productName: string;
    categoryId: number;
    unitPrice: number;
    discontinued: boolean;
    rowVersion: any;
    category: Category;
    orderDetail: OrderDetail[];
}