// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
import { EmployeeTerritories } from './EmployeeTerritories';

export interface Territory {
    territoryId: string;
    territoryDescription: string;
    employeeTerritories: EmployeeTerritories[];
}